:icons: font

== Provision BareMetal Cluster with Agent

The following steps were followed to get a cluster up and running on multiple bare metal hosts, with the abaility to scale out, or add clusters to the environment:

- Initial Cluster Definition - standard assets/install-config.yaml

- Using the Agent to deploy cluster - assets/agent-config.yaml

- Add LVM Storage - assets/post-install/lvm*.yaml

- Multi Cluster Engine -assets/post-install/mce*.yaml

-- oc patch provisioning provisioning-configuration --type merge -p '{"spec":{"watchAllNamespaces": true }}'


== Install Virtual BMC

On your vbmc machine:
 
- Install KCLI - https://github.com/karmab/kcli

  curl -s https://raw.githubusercontent.com/karmab/kcli/main/install.sh | bash
  
 - Setup ~/.kcli/config.yaml for your specific provider (AWS,IBM,GCP,LibVirt, KubeVirt, Openstack, OVirt, VSphere)
   Only providers with storage providers supports REDFISH+VIRTUALMEDIA
 - Change curl default behaviour for curl
    echo "insecure" > ~/.curlrc
    
 (have to figure out why ip instead of host name in acm)
 
 


